### ISSUE TITLE
Unhandled Exception error when running pynput. please help

### ISSUE THREAD

**Issue by mjmedeiros1701** [mbw8421/ff7_rebirth_piano#3]
Greetings!

i've been following your instructions and everything has worked up until i run main.py. At this point once i enter the name of the song, i always get the following error right before i can click the PS Remote Play window. I've tried a couple different songs with the same or similar error given. any help resolving this would be appreciated. I downloaded the latest version of python 3.13.

Which song would you like to play? tifa's theme
Click onto the PS Remote Play / Chiaki window
Unhandled exception in listener callback
Traceback (most recent call last):
  File "D:\Users\Mike\Desktop\ff7_rebirth_piano-master\venv\Lib\site-packages\pynput\_util\win32.py", line 386, in _handler
    converted = self._convert(code, msg, lpdata)
  File "D:\Users\Mike\Desktop\ff7_rebirth_piano-master\venv\Lib\site-packages\pynput\_util\win32.py", line 401, in _convert
    raise NotImplementedError()
NotImplementedError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Users\Mike\Desktop\ff7_rebirth_piano-master\venv\Lib\site-packages\pynput\_util\__init__.py", line 229, in inner
    return f(self, *args, **kwargs)
  File "D:\Users\Mike\Desktop\ff7_rebirth_piano-master\venv\Lib\site-packages\pynput\_util\win32.py", line 390, in _handler
    self._handle(code, msg, lpdata)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
TypeError: '_thread._ThreadHandle' object is not callable

**Comment by milkyboobs** [comment]
I had this too - it is due to some new handling of the mouse listener in newer python versions. Try installing python 3.11.6 or younger (python 3.9 can work too).
